/**
 * Nocked Bow Database — Static Seed Data
 *
 * IMPORTANT: Specifications are sourced from publicly available manufacturer
 * data and should be verified against official owner's manuals before use in
 * tuning decisions. Data is provided as a starting reference only.
 *
 * Starting manufacturers: Mathews, Hoyt, PSE, Prime, Bear
 * Starting years: 2020–2025
 */

import { BowSpec, ModuleDrawLengthMap } from '@/types';

// ─── Mathews ──────────────────────────────────────────────────────────────────

const mathewsBows: BowSpec[] = [
  {
    id: 'mathews-phase4-33-2022',
    manufacturer: 'Mathews',
    model: 'Phase 4 33',
    year: 2022,
    drawWeightMin: 55,
    drawWeightMax: 75,
    drawLengthMin: 26,
    drawLengthMax: 30,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 33,
    camType: 'Hybrid',
    letOff: 80,
    massWeight: 4.43,
    iboSpeed: 342,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 57.75,
    cableLengths: [37.5],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 26 },
      { position: '2', drawLength: 26.5 },
      { position: '3', drawLength: 27 },
      { position: '4', drawLength: 27.5 },
      { position: '5', drawLength: 28 },
      { position: '6', drawLength: 28.5 },
      { position: '7', drawLength: 29 },
      { position: '8', drawLength: 29.5 },
      { position: '9', drawLength: 30 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Shims are placed between the cam and the limb fork. Add shims to the top cam to move arrow left (RH) or add to bottom cam to move arrow right (RH). Use Mathews cam shim kit. Bow press required.',
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'mathews-v3x-33-2023',
    manufacturer: 'Mathews',
    model: 'V3X 33',
    year: 2023,
    drawWeightMin: 55,
    drawWeightMax: 75,
    drawLengthMin: 26,
    drawLengthMax: 30,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 33,
    camType: 'Hybrid',
    letOff: 80,
    massWeight: 4.4,
    iboSpeed: 343,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 57.75,
    cableLengths: [37.5],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 26 },
      { position: '2', drawLength: 26.5 },
      { position: '3', drawLength: 27 },
      { position: '4', drawLength: 27.5 },
      { position: '5', drawLength: 28 },
      { position: '6', drawLength: 28.5 },
      { position: '7', drawLength: 29 },
      { position: '8', drawLength: 29.5 },
      { position: '9', drawLength: 30 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Shims are placed between the cam and the limb fork. Add shims to the top cam to move arrow left (RH) or add to bottom cam to move arrow right (RH). Use Mathews cam shim kit. Bow press required.',
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'mathews-lift-33-5-2024',
    manufacturer: 'Mathews',
    model: 'Lift 33.5',
    year: 2024,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 6.25,
    braceHeightMax: 6.75,
    axleToAxle: 33.5,
    camType: 'Hybrid',
    letOff: 85,
    massWeight: 4.55,
    iboSpeed: 330,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 59,
    cableLengths: [38.25],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
      { position: '12', drawLength: 30.5 },
      { position: '13', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Shims are placed between the cam and the limb fork. Use Mathews cam shim kit. Bow press required.',
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'mathews-halon-32-2021',
    manufacturer: 'Mathews',
    model: 'Halon 32',
    year: 2021,
    drawWeightMin: 40,
    drawWeightMax: 80,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 5.75,
    braceHeightMax: 6,
    axleToAxle: 32,
    camType: 'Hybrid',
    letOff: 80,
    massWeight: 4.35,
    iboSpeed: 340,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 56.5,
    cableLengths: [37],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Use Mathews cam shim kit. Bow press required. Add shims to top cam to walk arrow left (RH).',
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
];

// ─── Hoyt ─────────────────────────────────────────────────────────────────────

const hoytBows: BowSpec[] = [
  {
    id: 'hoyt-ventum-33-2022',
    manufacturer: 'Hoyt',
    model: 'Ventum 33',
    year: 2022,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 6.25,
    braceHeightMax: 6.75,
    axleToAxle: 33,
    camType: 'Binary',
    letOff: 80,
    massWeight: 4.4,
    iboSpeed: 340,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 57.5,
    cableLengths: [37.75, 35.75],
    moduleDrawLengthMap: [
      { position: 'A1', drawLength: 25 },
      { position: 'A2', drawLength: 25.5 },
      { position: 'A3', drawLength: 26 },
      { position: 'B1', drawLength: 26.5 },
      { position: 'B2', drawLength: 27 },
      { position: 'B3', drawLength: 27.5 },
      { position: 'C1', drawLength: 28 },
      { position: 'C2', drawLength: 28.5 },
      { position: 'C3', drawLength: 29 },
      { position: 'D1', drawLength: 29.5 },
      { position: 'D2', drawLength: 30 },
      { position: 'D3', drawLength: 30.5 },
      { position: 'E1', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Hoyt uses a shim system on the cable rod (Pro Cam). Consult Hoyt owner\'s manual for shim placement. Bow press may be required.',
    limbPocketAdjustment: true,
    limbPocketInstructions:
      'Hoyt limb cups allow micro-adjust via set screws on the limb pockets. Adjust per-side independently to correct vertical cam lean. Consult owner\'s manual.',
    bowPressRequiredForModules: true,
  },
  {
    id: 'hoyt-rx-8-2023',
    manufacturer: 'Hoyt',
    model: 'RX-8',
    year: 2023,
    drawWeightMin: 30,
    drawWeightMax: 70,
    drawLengthMin: 24.5,
    drawLengthMax: 31,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 34,
    camType: 'Binary',
    letOff: 80,
    massWeight: 3.7,
    iboSpeed: 350,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 58.75,
    cableLengths: [38.5, 36.25],
    moduleDrawLengthMap: [
      { position: 'A1', drawLength: 24.5 },
      { position: 'A2', drawLength: 25 },
      { position: 'A3', drawLength: 25.5 },
      { position: 'B1', drawLength: 26 },
      { position: 'B2', drawLength: 26.5 },
      { position: 'B3', drawLength: 27 },
      { position: 'C1', drawLength: 27.5 },
      { position: 'C2', drawLength: 28 },
      { position: 'C3', drawLength: 28.5 },
      { position: 'D1', drawLength: 29 },
      { position: 'D2', drawLength: 29.5 },
      { position: 'D3', drawLength: 30 },
      { position: 'E1', drawLength: 30.5 },
      { position: 'E2', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Use Hoyt shim system. Consult owner\'s manual for correct shim placement location on this model.',
    limbPocketAdjustment: true,
    limbPocketInstructions:
      'Hoyt limb cup micro-adjust system. Consult owner\'s manual for limb pocket set screw locations.',
    bowPressRequiredForModules: true,
  },
  {
    id: 'hoyt-carbon-rx-8-ultra-2024',
    manufacturer: 'Hoyt',
    model: 'Carbon RX-8 Ultra',
    year: 2024,
    drawWeightMin: 30,
    drawWeightMax: 70,
    drawLengthMin: 24.5,
    drawLengthMax: 31,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 36,
    camType: 'Binary',
    letOff: 80,
    massWeight: 4.2,
    iboSpeed: 352,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 61,
    cableLengths: [39.5, 37.25],
    moduleDrawLengthMap: [
      { position: 'A1', drawLength: 24.5 },
      { position: 'A2', drawLength: 25 },
      { position: 'A3', drawLength: 25.5 },
      { position: 'B1', drawLength: 26 },
      { position: 'B2', drawLength: 26.5 },
      { position: 'B3', drawLength: 27 },
      { position: 'C1', drawLength: 27.5 },
      { position: 'C2', drawLength: 28 },
      { position: 'C3', drawLength: 28.5 },
      { position: 'D1', drawLength: 29 },
      { position: 'D2', drawLength: 29.5 },
      { position: 'D3', drawLength: 30 },
      { position: 'E1', drawLength: 30.5 },
      { position: 'E2', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Use Hoyt shim system on the cable guard rod or pigtail. Consult owner\'s manual.',
    limbPocketAdjustment: true,
    limbPocketInstructions:
      'Hoyt limb cup micro-adjust system. Consult owner\'s manual for limb pocket set screw locations.',
    bowPressRequiredForModules: true,
  },
  {
    id: 'hoyt-klash-2024',
    manufacturer: 'Hoyt',
    model: 'Klash',
    year: 2024,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 6.5,
    braceHeightMax: 7,
    axleToAxle: 30,
    camType: 'Binary',
    letOff: 80,
    massWeight: 3.9,
    iboSpeed: 332,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 54.75,
    cableLengths: [35.75, 33.5],
    moduleDrawLengthMap: [
      { position: 'A1', drawLength: 25 },
      { position: 'A2', drawLength: 25.5 },
      { position: 'B1', drawLength: 26 },
      { position: 'B2', drawLength: 26.5 },
      { position: 'C1', drawLength: 27 },
      { position: 'C2', drawLength: 27.5 },
      { position: 'D1', drawLength: 28 },
      { position: 'D2', drawLength: 28.5 },
      { position: 'E1', drawLength: 29 },
      { position: 'E2', drawLength: 29.5 },
      { position: 'F1', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: true,
  },
];

// ─── PSE ──────────────────────────────────────────────────────────────────────

const pseBows: BowSpec[] = [
  {
    id: 'pse-mach-34-2023',
    manufacturer: 'PSE',
    model: 'Mach 34',
    year: 2023,
    drawWeightMin: 50,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 6.25,
    braceHeightMax: 6.75,
    axleToAxle: 34,
    camType: 'Single',
    letOff: 80,
    massWeight: 4.5,
    iboSpeed: 350,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 58.25,
    cableLengths: [38.5],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
      { position: '12', drawLength: 30.5 },
      { position: '13', drawLength: 31 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    specialtyTuningSystems:
      'PSE Evolve Cam System. Modules changed by loosening set screws and rotating cam module disc.',
    bowPressRequiredForModules: false,
  },
  {
    id: 'pse-evo-nxt-33-2022',
    manufacturer: 'PSE',
    model: 'EVO NXT 33',
    year: 2022,
    drawWeightMin: 50,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 33,
    camType: 'Binary',
    letOff: 80,
    massWeight: 4.45,
    iboSpeed: 340,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 57,
    cableLengths: [38, 36],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
      { position: '12', drawLength: 30.5 },
      { position: '13', drawLength: 31 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'pse-mach-30-2024',
    manufacturer: 'PSE',
    model: 'Mach 30',
    year: 2024,
    drawWeightMin: 50,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 6.25,
    braceHeightMax: 6.75,
    axleToAxle: 30,
    camType: 'Single',
    letOff: 80,
    massWeight: 4.3,
    iboSpeed: 345,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 55,
    cableLengths: [36],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    specialtyTuningSystems: 'PSE Evolve Cam System.',
    bowPressRequiredForModules: false,
  },
];

// ─── Prime ────────────────────────────────────────────────────────────────────

const primeBows: BowSpec[] = [
  {
    id: 'prime-black-5-2023',
    manufacturer: 'Prime',
    model: 'Black 5',
    year: 2023,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 6.375,
    braceHeightMax: 6.625,
    axleToAxle: 35,
    camType: 'Binary',
    letOff: 80,
    massWeight: 4.2,
    iboSpeed: 335,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 60.25,
    cableLengths: [38.25, 35.5],
    moduleDrawLengthMap: [
      { position: 'A', drawLength: 25 },
      { position: 'B', drawLength: 25.5 },
      { position: 'C', drawLength: 26 },
      { position: 'D', drawLength: 26.5 },
      { position: 'E', drawLength: 27 },
      { position: 'F', drawLength: 27.5 },
      { position: 'G', drawLength: 28 },
      { position: 'H', drawLength: 28.5 },
      { position: 'I', drawLength: 29 },
      { position: 'J', drawLength: 29.5 },
      { position: 'K', drawLength: 30 },
      { position: 'L', drawLength: 30.5 },
      { position: 'M', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Prime uses a parallel cam system (PCO). Cam shimming available via shim kit. Contact Prime or authorized dealer for specific shim placement. Bow press required.',
    limbPocketAdjustment: false,
    bowPressRequiredForModules: true,
  },
  {
    id: 'prime-nexus-2024',
    manufacturer: 'Prime',
    model: 'Nexus',
    year: 2024,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 6.375,
    braceHeightMax: 6.625,
    axleToAxle: 35,
    camType: 'Binary',
    letOff: 85,
    massWeight: 4.3,
    iboSpeed: 334,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 60.25,
    cableLengths: [38.25, 35.5],
    moduleDrawLengthMap: [
      { position: 'A', drawLength: 25 },
      { position: 'B', drawLength: 25.5 },
      { position: 'C', drawLength: 26 },
      { position: 'D', drawLength: 26.5 },
      { position: 'E', drawLength: 27 },
      { position: 'F', drawLength: 27.5 },
      { position: 'G', drawLength: 28 },
      { position: 'H', drawLength: 28.5 },
      { position: 'I', drawLength: 29 },
      { position: 'J', drawLength: 29.5 },
      { position: 'K', drawLength: 30 },
      { position: 'L', drawLength: 30.5 },
      { position: 'M', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Prime PCO parallel cam system. Cam shimming available. Bow press required.',
    limbPocketAdjustment: false,
    bowPressRequiredForModules: true,
  },
  {
    id: 'prime-inline-3-2022',
    manufacturer: 'Prime',
    model: 'Inline 3',
    year: 2022,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 6.125,
    braceHeightMax: 6.375,
    axleToAxle: 33,
    camType: 'Binary',
    letOff: 80,
    massWeight: 4.1,
    iboSpeed: 336,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 57.5,
    cableLengths: [37.25, 34.75],
    moduleDrawLengthMap: [
      { position: 'A', drawLength: 25 },
      { position: 'B', drawLength: 25.5 },
      { position: 'C', drawLength: 26 },
      { position: 'D', drawLength: 26.5 },
      { position: 'E', drawLength: 27 },
      { position: 'F', drawLength: 27.5 },
      { position: 'G', drawLength: 28 },
      { position: 'H', drawLength: 28.5 },
      { position: 'I', drawLength: 29 },
      { position: 'J', drawLength: 29.5 },
      { position: 'K', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: true,
  },
];

// ─── Bear ─────────────────────────────────────────────────────────────────────

const bearBows: BowSpec[] = [
  {
    id: 'bear-aloft-2023',
    manufacturer: 'Bear',
    model: 'Aloft',
    year: 2023,
    drawWeightMin: 45,
    drawWeightMax: 70,
    drawLengthMin: 25.5,
    drawLengthMax: 30,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 30,
    camType: 'Single',
    letOff: 80,
    massWeight: 3.8,
    iboSpeed: 335,
    limbBoltMaxTurns: 5,
    limbBoltLbsPerTurn: 3,
    stringLength: 54.5,
    cableLengths: [35.25],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25.5 },
      { position: '2', drawLength: 26 },
      { position: '3', drawLength: 26.5 },
      { position: '4', drawLength: 27 },
      { position: '5', drawLength: 27.5 },
      { position: '6', drawLength: 28 },
      { position: '7', drawLength: 28.5 },
      { position: '8', drawLength: 29 },
      { position: '9', drawLength: 29.5 },
      { position: '10', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'bear-verdict-2022',
    manufacturer: 'Bear',
    model: 'Verdict',
    year: 2022,
    drawWeightMin: 45,
    drawWeightMax: 70,
    drawLengthMin: 25.5,
    drawLengthMax: 30,
    braceHeightMin: 5.875,
    braceHeightMax: 6.125,
    axleToAxle: 30,
    camType: 'Single',
    letOff: 80,
    massWeight: 3.9,
    iboSpeed: 340,
    limbBoltMaxTurns: 5,
    limbBoltLbsPerTurn: 3,
    stringLength: 54.75,
    cableLengths: [35.5],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25.5 },
      { position: '2', drawLength: 26 },
      { position: '3', drawLength: 26.5 },
      { position: '4', drawLength: 27 },
      { position: '5', drawLength: 27.5 },
      { position: '6', drawLength: 28 },
      { position: '7', drawLength: 28.5 },
      { position: '8', drawLength: 29 },
      { position: '9', drawLength: 29.5 },
      { position: '10', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'bear-adapt-2021',
    manufacturer: 'Bear',
    model: 'Adapt',
    year: 2021,
    drawWeightMin: 45,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 6,
    braceHeightMax: 6.5,
    axleToAxle: 30,
    camType: 'Single',
    letOff: 80,
    massWeight: 4.0,
    iboSpeed: 332,
    limbBoltMaxTurns: 5,
    limbBoltLbsPerTurn: 3,
    stringLength: 54.5,
    cableLengths: [35],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
  {
    id: 'bear-origin-2024',
    manufacturer: 'Bear',
    model: 'Origin',
    year: 2024,
    drawWeightMin: 45,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 6,
    braceHeightMax: 6.5,
    axleToAxle: 30,
    camType: 'Single',
    letOff: 80,
    massWeight: 3.85,
    iboSpeed: 340,
    limbBoltMaxTurns: 5,
    limbBoltLbsPerTurn: 3,
    stringLength: 54.75,
    cableLengths: [35.25],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
    ],
    camShimmingAvailable: false,
    limbPocketAdjustment: false,
    bowPressRequiredForModules: false,
  },
];

// ─── Bowtech ──────────────────────────────────────────────────────────────────

const bowtechBows: BowSpec[] = [
  {
    id: 'bowtech-sr350-2023',
    manufacturer: 'Bowtech',
    model: 'SR350',
    year: 2023,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 31,
    braceHeightMin: 6,
    braceHeightMax: 6.5,
    axleToAxle: 35,
    camType: 'Binary',
    letOff: 80,
    massWeight: 4.3,
    iboSpeed: 350,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3.5,
    stringLength: 60,
    cableLengths: [38.75, 36.5],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
      { position: '12', drawLength: 30.5 },
      { position: '13', drawLength: 31 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Bowtech DeadLock limb cup system functions as both limb tilt and cam alignment adjustment. Consult Bowtech owner\'s manual for DeadLock set screw locations and adjustment procedure.',
    limbPocketAdjustment: true,
    limbPocketInstructions:
      'Bowtech DeadLock system. Four set screws per limb cup adjust limb tilt in all four directions. Consult owner\'s manual.',
    specialtyTuningSystems:
      'Bowtech DeadLock Limb Cup System — allows limb pocket micro-adjustment for cam timing and lean without a bow press.',
    bowPressRequiredForModules: true,
  },
  {
    id: 'bowtech-carbon-zion-2022',
    manufacturer: 'Bowtech',
    model: 'Carbon Zion',
    year: 2022,
    drawWeightMin: 40,
    drawWeightMax: 70,
    drawLengthMin: 25,
    drawLengthMax: 30,
    braceHeightMin: 6.125,
    braceHeightMax: 6.375,
    axleToAxle: 33,
    camType: 'Binary',
    letOff: 80,
    massWeight: 3.6,
    iboSpeed: 344,
    limbBoltMaxTurns: 6,
    limbBoltLbsPerTurn: 3,
    stringLength: 57.5,
    cableLengths: [37.25, 35],
    moduleDrawLengthMap: [
      { position: '1', drawLength: 25 },
      { position: '2', drawLength: 25.5 },
      { position: '3', drawLength: 26 },
      { position: '4', drawLength: 26.5 },
      { position: '5', drawLength: 27 },
      { position: '6', drawLength: 27.5 },
      { position: '7', drawLength: 28 },
      { position: '8', drawLength: 28.5 },
      { position: '9', drawLength: 29 },
      { position: '10', drawLength: 29.5 },
      { position: '11', drawLength: 30 },
    ],
    camShimmingAvailable: true,
    camShimmingInstructions:
      'Bowtech DeadLock system. Consult owner\'s manual.',
    limbPocketAdjustment: true,
    limbPocketInstructions:
      'Bowtech DeadLock limb cup system. Consult owner\'s manual.',
    specialtyTuningSystems: 'Bowtech DeadLock Limb Cup System.',
    bowPressRequiredForModules: true,
  },
];

// ─── Master Database ───────────────────────────────────────────────────────────

export const BOW_DATABASE: BowSpec[] = [
  ...mathewsBows,
  ...hoytBows,
  ...pseBows,
  ...primeBows,
  ...bearBows,
  ...bowtechBows,
];

export const MANUFACTURERS = ['Mathews', 'Hoyt', 'PSE', 'Prime', 'Bear', 'Bowtech', 'Other'] as const;

export type Manufacturer = typeof MANUFACTURERS[number];

// ─── Query Helpers ─────────────────────────────────────────────────────────────

export function getModelsByManufacturer(manufacturer: string): BowSpec[] {
  return BOW_DATABASE.filter((bow) => bow.manufacturer === manufacturer).sort(
    (a, b) => b.year - a.year
  );
}

export function getBowById(id: string): BowSpec | undefined {
  return BOW_DATABASE.find((bow) => bow.id === id);
}

export function getBowByManufacturerAndModel(
  manufacturer: string,
  model: string,
  year?: number
): BowSpec | undefined {
  return BOW_DATABASE.find(
    (bow) =>
      bow.manufacturer === manufacturer &&
      bow.model === model &&
      (year === undefined || bow.year === year)
  );
}

export function getModuleForDrawLength(
  bow: BowSpec,
  drawLength: number
): ModuleDrawLengthMap | undefined {
  // Find closest match
  return bow.moduleDrawLengthMap.reduce<ModuleDrawLengthMap | undefined>((best, entry) => {
    if (!best) return entry;
    return Math.abs(entry.drawLength - drawLength) < Math.abs(best.drawLength - drawLength)
      ? entry
      : best;
  }, undefined);
}

export function calculateDrawLengthFromWingspan(wingspan: number): number {
  return Math.round((wingspan / 2.5) * 2) / 2; // Round to nearest 0.5"
}
